In [1]:
import numpy as np


In [2]:
my_array = np.arange (10000)

In [3]:
my_array


array([   0,    1,    2, ..., 9997, 9998, 9999])

In [5]:
my_list(range(1000))

NameError: name 'my_list' is not defined

In [6]:
%time my_array = np.arange(1000)

Wall time: 0 ns


In [7]:
%time for_in range (10): my_array2=my_array*2

SyntaxError: invalid syntax (<unknown>, line 1)

In [8]:
"geração de número aleatórios"

'geração de número aleatórios'

In [9]:
data = np.random.randn (2 ,3)

In [10]:
data= np.random.randn(2, 3)

In [13]:
print data

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(data)? (<ipython-input-13-d5bd85cc9860>, line 1)

In [14]:
print(data)

[[ 0.42317654  0.59457749 -0.30908054]
 [-1.22249715 -1.17955959  0.54591058]]


In [15]:
data= np.random.rand(2, 3)

In [16]:
print(data)

[[0.9708325  0.53286458 0.39733909]
 [0.14691042 0.46251287 0.32824366]]


In [17]:
data= np.random.randint(2, size=10)

In [18]:
print(data)

[1 0 1 1 1 1 0 0 1 0]


In [19]:
data =np.random.randint(5, size=1)

In [20]:
print(data)

[2]


In [21]:
data =np.random.randint(5, size=10)

In [22]:
print(data)

[0 3 3 1 2 1 2 2 1 0]


In [23]:
data * 10

array([ 0, 30, 30, 10, 20, 10, 20, 20, 10,  0])

In [24]:
data/10

array([0. , 0.3, 0.3, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0. ])

In [25]:
data * data

array([0, 9, 9, 1, 4, 1, 4, 4, 1, 0])

In [26]:
data ** 2


array([0, 9, 9, 1, 4, 1, 4, 4, 1, 0], dtype=int32)

In [27]:
data *2

array([0, 6, 6, 2, 4, 2, 4, 4, 2, 0])

In [28]:
data *log10

NameError: name 'log10' is not defined

In [29]:
data + data

array([0, 6, 6, 2, 4, 2, 4, 4, 2, 0])

In [30]:
%time data

Wall time: 0 ns


array([0, 3, 3, 1, 2, 1, 2, 2, 1, 0])

In [32]:
%time data**2

Wall time: 0 ns


array([0, 9, 9, 1, 4, 1, 4, 4, 1, 0], dtype=int32)

In [33]:
data.shape

(10,)

In [34]:
"Atenção Matriz de dados, atenção às regras de operação com as informações"

'Atenção Matriz de dados, atenção às regras de operação com as informações'

In [35]:
arr1 = np.array ([1,2,3], dtype=np.float64)

In [36]:
arr2 =np.array ([1,2,3],dtype=np.int32)

In [37]:
arr1

array([1., 2., 3.])

In [38]:
arr2

array([1, 2, 3])

In [39]:
%time arr1

Wall time: 0 ns


array([1., 2., 3.])

In [40]:
%time arr2

Wall time: 0 ns


array([1, 2, 3])

In [41]:
"INDEXAÇÃO"

'INDEXAÇÃO'

In [42]:
a[0]

NameError: name 'a' is not defined

In [43]:
array [0]

NameError: name 'array' is not defined

In [44]:
>>> a[0]

NameError: name 'a' is not defined

In [45]:
>>> array{0}

SyntaxError: invalid syntax (<ipython-input-45-77e5542d0528>, line 1)

In [46]:
"ducked type - python: não declarativa, interpreta o tipo de dado e categoriza. Exemplo identificação núm int ou núm decimal"

'ducked type - python: não declarativa, interpreta o tipo de dado e categoriza. Exemplo identificação núm int ou núm decimal'

In [47]:
arr1[0]

1.0

In [48]:
arr2[0]

1

In [49]:
arr1[1]


2.0

In [53]:
"Sobreescrever dados indexados"

'Sobreescrever dados indexados'

In [50]:
arr1 [1] = 10

In [51]:
arr1 [1]

10.0

arr2.fill (100)

In [54]:
arr2.fill(100)

In [55]:
arr2

array([100, 100, 100])

In [56]:
my_array =np.arange (36)

In [57]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [58]:
my_array= reshape (6,6)

NameError: name 'reshape' is not defined

In [59]:
my_array.reshape (6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [60]:
"SLicing"

'SLicing'

In [61]:
my_array [0, 3:5]

IndexError: too many indices for array

In [62]:
"primeira posição linha segunda intervalo onde a segunda posição é fechada"

'primeira posição linha segunda intervalo onde a segunda posição é fechada'

In [63]:
my_array [0, 1:2]

IndexError: too many indices for array

In [64]:
array [(3,4)]

NameError: name 'array' is not defined

In [65]:
my_array [(3,4)]

IndexError: too many indices for array

In [66]:
"percorrer com-passo"

'percorrer com-passo'

In [67]:
my_array [1::1,::1]

IndexError: too many indices for array

In [69]:
"
Given [2, 1, 3, 5, 4], the function should return 3.
At the 0th moment only the 2nd bulb is turned on, but it does not shine because the previous one is not on.
At the 1st moment two bulbs are turned on (1st and 2nd) and both of them shine.
At the 2nd moment three bulbs are turned on (1st, 2nd and 3rd) and all of them shine.
At the 3rd moment four bulbs are turned on (1st, 2nd, 3rd and 5th), but the 5th bulb does not shine because the previous one is not turned on.
At the 4th moment five bulbs are turned on (1st, 2nd, 3rd, 4th and 5th) and all five of them shine. There are three moments (1st, 2nd and 4th) when every turned on bulb shines.
More sample cases:
A=[2, 3, 4, 1, 5], the function should return 2 (at the 3rd and 4th moment every turned on bulb shines).
A=[1, 3, 4, 2, 5], the function should return 3 (at the 0th, 3rd and 4th moment every turned on bulb shines). Assume that:
Furtive validation criteria: N is an integer within the range [1..100]; the elements of A are all distinct; each element of array A is an integer within the range [1..N].
"

SyntaxError: EOL while scanning string literal (<ipython-input-69-b3982240f296>, line 1)

In [70]:

Given [2, 1, 3, 5, 4], the function should return 3.
At the 0th moment only the 2nd bulb is turned on, but it does not shine because the previous one is not on.
At the 1st moment two bulbs are turned on (1st and 2nd) and both of them shine.
At the 2nd moment three bulbs are turned on (1st, 2nd and 3rd) and all of them shine.
At the 3rd moment four bulbs are turned on (1st, 2nd, 3rd and 5th), but the 5th bulb does not shine because the previous one is not turned on.
At the 4th moment five bulbs are turned on (1st, 2nd, 3rd, 4th and 5th) and all five of them shine. There are three moments (1st, 2nd and 4th) when every turned on bulb shines.
More sample cases:
A=[2, 3, 4, 1, 5], the function should return 2 (at the 3rd and 4th moment every turned on bulb shines).
A=[1, 3, 4, 2, 5], the function should return 3 (at the 0th, 3rd and 4th moment every turned on bulb shines). Assume that:
Furtive validation criteria: N is an integer within the range [1..100]; the elements of A are all distinct; each element of array A is an integer within the range [1..N].
"""

SyntaxError: invalid syntax (<ipython-input-70-310340388103>, line 1)

In [71]:
"[
Given [2, 1, 3, 5, 4], the function should return 3.
At the 0th moment only the 2nd bulb is turned on, but it does not shine because the previous one is not on.
At the 1st moment two bulbs are turned on (1st and 2nd) and both of them shine.
At the 2nd moment three bulbs are turned on (1st, 2nd and 3rd) and all of them shine.
At the 3rd moment four bulbs are turned on (1st, 2nd, 3rd and 5th), but the 5th bulb does not shine because the previous one is not turned on.
At the 4th moment five bulbs are turned on (1st, 2nd, 3rd, 4th and 5th) and all five of them shine. There are three moments (1st, 2nd and 4th) when every turned on bulb shines.
More sample cases:
A=[2, 3, 4, 1, 5], the function should return 2 (at the 3rd and 4th moment every turned on bulb shines).
A=[1, 3, 4, 2, 5], the function should return 3 (at the 0th, 3rd and 4th moment every turned on bulb shines). Assume that:
Furtive validation criteria: N is an integer within the range [1..100]; the elements of A are all distinct; each element of array A is an integer within the range [1..N].
"]


SyntaxError: EOL while scanning string literal (<ipython-input-71-7c4675aa2f5c>, line 1)

In [72]:
"[
Given [2, 1, 3, 5, 4], the function should return 3.
At the 0th moment only the 2nd bulb is turned on, but it does not shine because the previous one is not on.
At the 1st moment two bulbs are turned on (1st and 2nd) and both of them shine.
At the 2nd moment three bulbs are turned on (1st, 2nd and 3rd) and all of them shine.
At the 3rd moment four bulbs are turned on (1st, 2nd, 3rd and 5th), but the 5th bulb does not shine because the previous one is not turned on.
At the 4th moment five bulbs are turned on (1st, 2nd, 3rd, 4th and 5th) and all five of them shine. There are three moments (1st, 2nd and 4th) when every turned on bulb shines.
More sample cases:
A=[2, 3, 4, 1, 5], the function should return 2 (at the 3rd and 4th moment every turned on bulb shines).
A=[1, 3, 4, 2, 5], the function should return 3 (at the 0th, 3rd and 4th moment every turned on bulb shines). Assume that:
Furtive validation criteria: N is an integer within the range [1..100]; the elements of A are all distinct; each element of array A is an integer within the range [1..N].
    ]"

SyntaxError: EOL while scanning string literal (<ipython-input-72-ff1a0ece82aa>, line 1)

In [73]:
A = [2,1,3,5,4]

In [75]:
for i in range (len(A)):
    print (i, A[i],A[:i+1])

0 2 [2]
1 1 [2, 1]
2 3 [2, 1, 3]
3 5 [2, 1, 3, 5]
4 4 [2, 1, 3, 5, 4]


In [76]:
A

[2, 1, 3, 5, 4]

In [77]:
for x in range(0, 3):
    print "We're on time %d" % (x)

SyntaxError: invalid syntax (<ipython-input-77-52b6996ab2af>, line 2)

In [78]:
>>> import numpy as np
>>> a = np.array([2,3,4])
>>> a
array([2, 3, 4])
>>> a.dtype
dtype('int64')
>>> b = np.array([1.2, 3.5, 5.1])
>>> b.dtype
dtype('float64')


NameError: name 'array' is not defined

In [79]:
? np.array


In [80]:
? cumsum


Object ` cumsum` not found.


In [81]:
?cummsum


Object `cummsum` not found.


In [82]:
? np.cumsum


In [89]:
np.array=np.random.randint (10, 10)

ValueError: Range cannot be empty (low >= high) unless no samples are taken

In [92]:
Matriz = np.random.randint (10,15)

In [94]:
Matriz

13

In [96]:
? np.arange

In [97]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])